move_dict = {
'absorb':None
,'acid':None
,'acidarmor':None
,'agility':None
,'amnesia':None
,'aurorabeam':None
,'barrage':None
,'barrier':None
,'bide':None
,'bind':None
,'bite':None
,'blizzard':None
,'bodyslam':None
,'boneclub':None
,'bonemerang':None
,'bubble':None
,'bubblebeam':None
,'clamp':None
,'cometpunch':None
,'confuseray':None
,'confusion':None
,'constrict':None
,'conversion':None
,'counter':None
,'crabhammer':None
,'cut':None
,'defensecurl':None
,'dig':None
,'disable':None
,'dizzypunch':None
,'double_edge':None
,'doublekick':None
,'doubleslap':None
,'doubleteam':None
,'dragonrage':None
,'dreameater':None
,'drillpeck':None
,'earthquake':None
,'eggbomb':None
,'ember':None
,'explosion':None
,'fireblast':None
,'firepunch':None
,'firespin':None
,'fissure':None
,'flamethrower':None
,'flash':None
,'fly':None
,'focusenergy':None
,'furyattack':None
,'furyswipes':None
,'glare':None
,'growl':None
,'growth':None
,'guillotine':None
,"harden":None
,"haze":None
,"headbutt":None
,"hijumpkick":None
,"hornattack":None
,"horndrill":None
,"hydropump":None
,"hyperbeam":None
,"hyperfang":None
,"hypnosis":None
,"icebeam":None
,"icepunch":None
,"jumpkick":None
,"karatechop":None
,"kinesis":None
,"leechlife":None
,"leechseed":None
,"leer":None
,"lick":None
,"lightscreen":None
,"lovelykiss":None
,"lowkick":None
,"meditate":None
,"megadrain":None
,"megakick":None
,"megapunch":None
,"metronome":None
,"mimic":None
,"minimize":None
,"mirrormove":None
,"mist":None
,"nightshade":None
,"payday":None
,"peck":None
,"petaldance":None
,"pinmissile":None
,"poisongas":None
,"poisonpowder":None
,"poisonsting":None
,"pound":None
,"psybeam":None
,"psychic":None
,"psywave":None
,"quickattack":None
,"rage":None
,"razorleaf":None
,"razorwind":None
,"recover":None
,"reflect":None
,"rest":None
,"roar":None
,"rockslide":None
,"rockthrow":None
,"sand_attack":None
,"scratch":None
,"screech":None
,"seismictoss":None
,"self_destruct":None
,"sharpen":None
,"sing":None
,"skullbash":None
,"skyattack":None
,"slam":None
,"slash":None
,"sleeppowder":None
,"sludge":None
,"smog":None
,"smokescreen":None
,"soft_boiled":None
,"solarbeam":None
,"sonicboom":None
,"spikecannon":None
,"splash":None
,"spore":None
,"stomp":None
,"strength":None
,"stringshot":None
,"struggle":None
,"stunspore":None
,"submission":None
,"substitute":None
,"superfang":None
,"supersonic":None
,"surf":None
,"swift":None
,"swordsdance":None
,"tackle":None
,"tailwhip":None
,"takedown":None
,"teleport":None
,"thrash":None
,"thunder":None
,"thunderbolt":None
,"thunderpunch":None
,"thundershock":None
,"thunderwave":None
,"toxic":None
,"transform":None
,"triattack":None
,"twineedle":None
,"vicegrip":None
,"vinewhip":None
,"waterfall":None
,"watergun":None
,"whirlwind":None
,"wingattack":None
,"withdraw":None
,}